### ISSUE TITLE
Unable to make the picker work with Umbraco 7.10

### ISSUE THREAD

**Issue by tormnator** [OPTEN/OP10-Multiple-Media-Picker#17]
I installed the package into an Umbraco 7.10 site today, but am not able to use the features. There are no fields visible other than the media path in the right-hand sidebar/dialog, and there are no "quick-view properties" visible either.

Has anyone tested this package with the newer Umbraco releases?

**Comment by AaronMorf** [comment]
Did you select them at the data type settings? it should work!
![image](https://user-images.githubusercontent.com/10773071/51536451-ea12ec80-1e4b-11e9-9b7d-823b9dcde397.png)

**Comment by tormnator** [comment]
Just installed the latest OP10 Multiple Media Picker package from Umbraco and replaced an Umbraco.MediaPicker2 with the OP10 picker:

1. The original image got lost -> I had change back to the MediaPicker2 and record which image was there, then change to OP10 again and reselect the image. Would be nice if that wasn't necessary.

2. I still don't see any properties for selection (checking off) in the settings. Here's a screenshot:

![image](https://user-images.githubusercontent.com/15617453/51553221-867ac600-1e2f-11e9-8d82-688d8b03ca77.png)

Maybe only properties added to custom media types are supported? But that would defeat one of my reasons for using this package, to be able to rename the physical file (and ultimately the image url).

-Tor

**Comment by AaronMorf** [comment]
Thanks for your reply!
1. I fixed this error. It is because of the new udi and not anymore the id. It will be fixed in the next release.
2. Currently you need to hit save after you changed the "Allow items of type" field. Then it will search for the available properties. 
As default, there is always the Name for any type. For the Image there is also the physical name as long as there is a "umbracoFile" alias which is default for the Image.
If you still have the error you may can try to change it to File, hit save and look if that works. If it still fails, I would be glad if you could send me the Error from the Console (F12).

-Aaron
